# Generated by Django 3.2 on 2023-07-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('category', models.CharField(choices=[('CR', 'Crud'), ('MI', 'Milk'), ('LS', 'Lassi'), ('CR', 'Crud'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CZ', 'Cheese'), ('IS', 'IceCreame')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
            options={
                'db_table': 'Store',
            },
        ),
    ]
